### ISSUE TITLE
checklist

### ISSUE THREAD

**Issue by tingwei628** [stanleyexp/uniquep#20]
## Feature
[以"美國"一詞為例]
1. 漢語拼音(pinyin)方面 
- [x] (1)含聲調的漢語拼音                [mei3 guo2]
- [x] (2)不含聲調的漢語拼音              [mei guo]
2. 國際音標(IPA)方面 
- [x] (3) 含聲調的國際音標               [meɪ3 kuɔ2]
- [x] (4) 不含聲調的國際音標             [meɪ kuɔ]
- [ ] (5) 該詞有幾個國際音標             [6]
3. 語音獨特點(UP)
- [x] (6) 語音獨特點的位置               假設是[4]
- [x] (7) 語音獨特點是哪個國際音標        [k]
4. 聲調(tone)
- [ ] (8)裡面每個字的聲調                [3,2]

---
5.  語音獨特點
- [ ] (9)語音獨特點的位置篩選

**Comment by tingwei628** [comment]
## Refactor

- [ ] add [conditional decorator](https://stackoverflow.com/questions/10724854/how-to-do-a-conditional-decorator-in-python) which tell has_tone/no_tone
- [ ] `@staticmethod`/`@classmethod` to replace global functions
